gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#fab388"
      - "bold"
    cherryPickedCommitBgColor:
      - "#f2cdce"
    cherryPickedCommitFgColor:
      - "#89b4fb"
    defaultFgColor:
      - "#cdd6f5"
    inactiveBorderColor:
      - "#89b4fb"
    optionsTextColor:
      - "#89b4fb"
    searchingActiveBorderColor:
      - "#fab388"
      - "bold"
    selectedLineBgColor:
      - "#45475b"
    unstagedChangesColor:
      - "#f38ba9"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  merging:
    args: "--no-ff"
customCommands:
  - command: >
      git commit  -m '{{.Form.Type}}{{if .Form.Scope}}({{.Form.Scope}}){{end}}{{.Form.Breaking}}: {{.Form.Message}}'  {{if .Form.Description}}-m '{{.Form.Description}}'{{end}}

    context: files
    description: "Create new conventional commit with emoji and optional description"
    key: C
    prompts:
      - type: "menu"
        key: "Type"
        title: "Type of change"
        options:
          - name: "✨ feat - A new feature"
            value: "feat"
          - name: "🐛 fix - A bug fix"
            value: "fix"
          - name: "📝 docs - Documentation only changes"
            value: "docs"
          - name: "🎨 style - Code style changes (formatting, etc)"
            value: "style"
          - name: "♻️ refactor - Code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "🚀 perf - A code change that improves performance"
            value: "perf"
          - name: "✅ test - Adding missing tests or correcting existing tests"
            value: "test"
          - name: "🔧 chore - Changes to the build process or auxiliary tools"
            value: "chore"
          - name: "👷 ci - Changes to CI configuration files and scripts"
            value: "ci"
          - name: "📦 build - Changes that affect the build system or dependencies"
            value: "build"
          - name: "⏪ revert - Reverts a previous commit"
            value: "revert"
      - type: "input"
        title: "Scope"
        key: "Scope"
        initialValue: ""
      - type: "menu"
        key: "Breaking"
        title: "Breaking change?"
        options:
          - name: "no"
            value: ""
          - name: "yes"
            value: "!"
      - type: "input"
        title: "Commit Message"
        key: "Message"
        initialValue: ""
      - type: "input"
        title: "Commit Description (Optional)"
        key: "Description"
        initialValue: ""
      - type: "confirm"
        key: "Confirm"
        title: "Commit"
        body: "Are you sure you want to commit?"
    loadingText: "Creating commit..."
  - key: "G"
    command: "glab mr view -w {{.SelectedLocalBranch.UpstreamBranch}}"
    context: "localBranches"
    description: "Go to MR in gitlab"
    stream: true
