gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#fab388"
      - "bold"
    cherryPickedCommitBgColor:
      - "#f2cdce"
    cherryPickedCommitFgColor:
      - "#89b4fb"
    defaultFgColor:
      - "#cdd6f5"
    inactiveBorderColor:
      - "#89b4fb"
    optionsTextColor:
      - "#89b4fb"
    searchingActiveBorderColor:
      - "#fab388"
      - "bold"
    selectedLineBgColor:
      - "#45475b"
    unstagedChangesColor:
      - "#f38ba9"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  merging:
    args: "--no-ff"
customCommands:
  - command: >
      {{ $scope := "" }}{{ if .Form.Scope }}{{ $scope = printf "(%s)" .Form.Scope }}{{ end }}git commit -m {{ printf "%s%s%s: %s" .Form.Type $scope .Form.Breaking .Form.Message | quote }}{{ if .Form.Description }} -m {{ .Form.Description | quote }}{{ end }}

    context: files
    description: "Create conventional commit (scope/breaking/description optional)"
    key: C
    prompts:
      - type: "menu"
        key: "Type"
        title: "Type of change"
        options:
          - name: "✨ feat - A new feature"
            value: "feat"
            key: f
          - name: "🐛 fix - A bug fix"
            value: "fix"
            key: x
          - name: "📝 docs - Documentation only changes"
            value: "docs"
            key: d
          - name: "🎨 style - Code style changes (formatting, etc)"
            value: "style"
            key: s
          - name: "♻️ refactor - Code change that neither fixes a bug nor adds a feature"
            value: "refactor"
            key: r
          - name: "🚀 perf - A code change that improves performance"
            value: "perf"
            key: p
          - name: "✅ test - Adding missing tests or correcting existing tests"
            value: "test"
            key: t
          - name: "🔧 chore - Changes to the build process or auxiliary tools"
            value: "chore"
            key: c
          - name: "👷 ci - Changes to CI configuration files and scripts"
            value: "ci"
            key: i
          - name: "📦 build - Changes that affect the build system or dependencies"
            value: "build"
            key: b
          - name: "⏪ revert - Reverts a previous commit"
            value: "revert"
            key: v
      - type: "input"
        title: "Scope"
        key: "Scope"
        initialValue: ""
      - type: "menu"
        key: "Breaking"
        title: "Breaking change?"
        options:
          - name: "no"
            value: ""
          - name: "yes"
            value: "!"
      - type: "input"
        title: "Commit Message"
        key: "Message"
        initialValue: ""
      - type: "input"
        title: "Commit Description (Optional)"
        key: "Description"
        initialValue: ""
      - type: "confirm"
        key: "Confirm"
        title: "Commit"
        body: "Are you sure you want to commit?"
    loadingText: "Creating commit..."
  - key: "G"
    command: "glab mr view -w {{ if .SelectedLocalBranch.UpstreamBranch }}{{ .SelectedLocalBranch.UpstreamBranch | quote }}{{ end }}"
    context: "localBranches"
    description: "Go to MR in gitlab"
    loadingText: "Opening MR in browser..."
