windowrule = float on, match:class (org.pulseaudio.pavucontrol)
windowrule = float on, match:class (blueman-manager)
windowrule = float on, match:class (^zoom$)
windowrule = float on, match:class (org.qbittorrent.qBittorrent)
windowrule = float on, match:class (anki)
windowrule = idle_inhibit fullscreen, match:class .*
