[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1
[default_session]
command = "tuigreet --cmd Hyprland --asteriks --remember --time --greeting 'Show must go on.'"
user = "greeter"
