[mgr]
ratio = [0, 4 , 3]

[opener]
video = [
	{ run = 'celluloid "$@"'},
]
open = [
    { run = 'xdg-open "$@"'}
]
document = [
	{ run = 'zathura "$@"', for = "unix" },
]

[open]
prepend_rules = [
	{ name = "*.pdf", use = "document" },
]
rules = [
	{ mime = "video/*", use = "video" },
    { mime = "image/*", use = "open"}
]
